name: ci

on:
  push:
    branches: [ video ]
  pull_request:
    branches: [ video ]

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Set up python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements-dev.txt

      - name: Test with pytest
        run: pytest
  build:
      runs-on: ubuntu-latest
      needs: tests
      steps:
        - name: login heroku
          uses: actions/checkout@v2
          env:
            HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
          run: heroku container:login

        - name: Build Docker Image
          run: docker build -t hwcontainer:latest .
        - name: Push the docker image to the heroku
          env:
            HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
          run:
            heroku container:push hwcontainer --app ${{ secrets.HEROKU_APP_NAME }}
            heroku container:release heroku container --app ${{ secrets.HEROKU_APP_NAME }}
            heroku ps:scale heroku container:=1 -a ${{ secrets.HEROKU_APP_NAME }}
