version: "3.9"

services:
  django:
    build: .
    container_name: django
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/usr/src/app
    ports:
      - "8000:8000"
    depends_on:
      - migration
      - postgresqldb

  postgresqldb:
    image: postgres
    environment:
      - POSTGRES_DB=netology_stocks_products
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=12345
    container_name: postgresqldb
    volumes:
      - pgdbdata:/var/lib/postgresql/data/
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  migration:
    image: new_python
    build: .
    command: python manage.py migrate --noinput
    depends_on:
      postgresqldb:
        condition: service_healthy

volumes:
  pgdbdata: null
