

# создание продукта
POST http://localhost:8000/api/v1/products/
Content-Type: application/json

{
  "id": 2,
  "title": "Перец болгарский",
  "description": "Лучшие перцы на рынке"
}

###

# получение продуктов
GET http://localhost:8000/api/v1/products/?page=1
Content-Type: application/json

###

# обновление продукта
PATCH http://localhost:8000/api/v1/products/1/
Content-Type: application/json

{
  "description": "Самые сочные и ароматные помидорки"
}

###

# удаление продукта
DELETE http://localhost:8000/api/v1/stocks/2/
Content-Type: application/json

###

# поиск продуктов по названию и описанию
GET http://localhost:8000/api/v1/products/?search=перец
Content-Type: application/json

###

# создание склада
POST http://localhost:8000/api/v1/stocks/
Content-Type: application/json

{
  "address": "new адрес",
  "positions": [
    {
      "product": 6,
      "quantity": 250,
      "price": 100.50
    },
    {
      "product": 9,
      "quantity": 100,
      "price": 100
    },
     {
      "product": 10,
      "quantity": 600,
      "price": 230.50
    }
  ]
}

###

# обновляем записи на складе
PATCH http://localhost:8000/api/v1/stocks/3/
Content-Type: application/json

{
  "positions": [
    {
      "product": 4,
      "quantity": 100,
      "price": 130.80
    },
    {
      "product": 3,
      "quantity": 243,
      "price": 145
    }
  ]
}

###

# поиск складов, где есть определенный продукт
GET http://localhost:8000/api/v1/stocks/?products=пе
Content-Type: application/json
